name: GitHub Actions

on:
  push:
    branches:
    - test2

jobs:
  test:
    name: CUDA
    runs-on: [self-hosted, linux]
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Test CUDA
        shell: bash
        run: |
          export TASK="${{ matrix.task }}"
          export COMPILER="${{ matrix.compiler }}"
          export GITHUB_ACTIONS="true"
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          nvidia-smi -f log.txt
          cat log.txt
          sudo docker run --rm --gpus all nvidia/cuda:10.0-base nvidia-smi
          $GITHUB_WORKSPACE/.ci/setup.sh
          $GITHUB_WORKSPACE/.ci/test.sh
