name: GitHub Actions

on:
  push:
    branches:
    - test2

jobs:
  test:
    name: CUDA
    runs-on: [self-hosted, linux]
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Test CUDA
        shell: bash
        run: |
          curl -sL https://cmake.org/files/v3.18/cmake-3.18.1-Linux-x86_64.sh -o cmake.sh
          chmod +x cmake.sh
          sudo ./cmake.sh --prefix=/usr/local --exclude-subdir
          rm cmake.sh
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
          lspci -vnn | grep -i VGA -A 12
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y nvidia-docker2
          sudo systemctl restart docker
          nvidia-smi -f log.txt
          cat log.txt
          sudo docker run -e TASK=cuda -e COMPILER=gcc -e GITHUB_ACTIONS=true -e OS_NAME=linux -e BUILD_DIRECTORY="$GITHUB_WORKSPACE" -e CONDA_ENV="test-env" -e CONDA="$HOME/miniconda" -e PATH="$CONDA/bin:${HOME}/.local/bin:$PATH" -v "$GITHUB_WORKSPACE":"/lightgbm" --rm --gpus all nvidia/cuda:11.0-runtime /bin/bash -c "apt-get install --no-install-recommends -y wget && nvidia-smi && /lightgbm/.ci/setup.sh && /lightgbm/.ci/test.sh"
