name: GitHub Actions

on:
  push:
    branches:
    - test2

jobs:
  test:
    name: CUDA
    runs-on: [self-hosted, linux]
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Test CUDA
        shell: bash
        run: |
          export TASK=cuda
          export COMPILER=gcc
          export GITHUB_ACTIONS="true"
          export OS_NAME="linux"
          export BUILD_DIRECTORY="$GITHUB_WORKSPACE"
          export CONDA_ENV="test-env"
          export CONDA="$HOME/miniconda"
          export PATH="$CONDA/bin:${HOME}/.local/bin:$PATH"
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
          lspci -vnn | grep -i VGA -A 12
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y nvidia-docker2
          sudo systemctl restart docker
          nvidia-smi -f log.txt
          cat log.txt
          sudo docker run --rm --gpus all nvidia/cuda:10.0-base nvidia-smi
          $GITHUB_WORKSPACE/.ci/setup.sh
          $GITHUB_WORKSPACE/.ci/test.sh
